// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wso2/discovery/api/Resource.proto

package org.wso2.choreo.connect.discovery.api;

/**
 * <pre>
 * Resource config model
 * </pre>
 *
 * Protobuf type {@code wso2.discovery.api.Resource}
 */
public final class Resource extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:wso2.discovery.api.Resource)
    ResourceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Resource.newBuilder() to construct.
  private Resource(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Resource() {
    id_ = "";
    path_ = "";
    endpointSecurity_ = java.util.Collections.emptyList();
    schemes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    methods_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    scopesList_ = java.util.Collections.emptyList();
    tier_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Resource();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Resource(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            path_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              endpointSecurity_ = new java.util.ArrayList<org.wso2.choreo.connect.discovery.api.SecurityInfo>();
              mutable_bitField0_ |= 0x00000001;
            }
            endpointSecurity_.add(
                input.readMessage(org.wso2.choreo.connect.discovery.api.SecurityInfo.parser(), extensionRegistry));
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              security_ = com.google.protobuf.MapField.newMapField(
                  SecurityDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            security__ = input.readMessage(
                SecurityDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            security_.getMutableMap().put(
                security__.getKey(), security__.getValue());
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              schemes_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            schemes_.add(s);
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              methods_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000008;
            }
            methods_.add(s);
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000010) != 0)) {
              scopesList_ = new java.util.ArrayList<org.wso2.choreo.connect.discovery.api.SecurityList>();
              mutable_bitField0_ |= 0x00000010;
            }
            scopesList_.add(
                input.readMessage(org.wso2.choreo.connect.discovery.api.SecurityList.parser(), extensionRegistry));
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            tier_ = s;
            break;
          }
          case 72: {

            disableSecurity_ = input.readBool();
            break;
          }
          case 82: {
            org.wso2.choreo.connect.discovery.api.OperationPolicies.Builder subBuilder = null;
            if (policies_ != null) {
              subBuilder = policies_.toBuilder();
            }
            policies_ = input.readMessage(org.wso2.choreo.connect.discovery.api.OperationPolicies.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(policies_);
              policies_ = subBuilder.buildPartial();
            }

            break;
          }
          case 90: {
            org.wso2.choreo.connect.discovery.api.EndpointCluster.Builder subBuilder = null;
            if (endpoints_ != null) {
              subBuilder = endpoints_.toBuilder();
            }
            endpoints_ = input.readMessage(org.wso2.choreo.connect.discovery.api.EndpointCluster.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(endpoints_);
              endpoints_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        endpointSecurity_ = java.util.Collections.unmodifiableList(endpointSecurity_);
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        schemes_ = schemes_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000008) != 0)) {
        methods_ = methods_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000010) != 0)) {
        scopesList_ = java.util.Collections.unmodifiableList(scopesList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.wso2.choreo.connect.discovery.api.ResourceProto.internal_static_wso2_discovery_api_Resource_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 4:
        return internalGetSecurity();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.wso2.choreo.connect.discovery.api.ResourceProto.internal_static_wso2_discovery_api_Resource_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.wso2.choreo.connect.discovery.api.Resource.class, org.wso2.choreo.connect.discovery.api.Resource.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PATH_FIELD_NUMBER = 2;
  private volatile java.lang.Object path_;
  /**
   * <code>string path = 2;</code>
   * @return The path.
   */
  @java.lang.Override
  public java.lang.String getPath() {
    java.lang.Object ref = path_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      path_ = s;
      return s;
    }
  }
  /**
   * <code>string path = 2;</code>
   * @return The bytes for path.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPathBytes() {
    java.lang.Object ref = path_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      path_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENDPOINTSECURITY_FIELD_NUMBER = 3;
  private java.util.List<org.wso2.choreo.connect.discovery.api.SecurityInfo> endpointSecurity_;
  /**
   * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 3;</code>
   */
  @java.lang.Override
  public java.util.List<org.wso2.choreo.connect.discovery.api.SecurityInfo> getEndpointSecurityList() {
    return endpointSecurity_;
  }
  /**
   * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.wso2.choreo.connect.discovery.api.SecurityInfoOrBuilder> 
      getEndpointSecurityOrBuilderList() {
    return endpointSecurity_;
  }
  /**
   * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 3;</code>
   */
  @java.lang.Override
  public int getEndpointSecurityCount() {
    return endpointSecurity_.size();
  }
  /**
   * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 3;</code>
   */
  @java.lang.Override
  public org.wso2.choreo.connect.discovery.api.SecurityInfo getEndpointSecurity(int index) {
    return endpointSecurity_.get(index);
  }
  /**
   * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 3;</code>
   */
  @java.lang.Override
  public org.wso2.choreo.connect.discovery.api.SecurityInfoOrBuilder getEndpointSecurityOrBuilder(
      int index) {
    return endpointSecurity_.get(index);
  }

  public static final int SECURITY_FIELD_NUMBER = 4;
  private static final class SecurityDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                org.wso2.choreo.connect.discovery.api.ResourceProto.internal_static_wso2_discovery_api_Resource_SecurityEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> security_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetSecurity() {
    if (security_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          SecurityDefaultEntryHolder.defaultEntry);
    }
    return security_;
  }

  public int getSecurityCount() {
    return internalGetSecurity().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; security = 4;</code>
   */

  @java.lang.Override
  public boolean containsSecurity(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetSecurity().getMap().containsKey(key);
  }
  /**
   * Use {@link #getSecurityMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getSecurity() {
    return getSecurityMap();
  }
  /**
   * <code>map&lt;string, string&gt; security = 4;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getSecurityMap() {
    return internalGetSecurity().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; security = 4;</code>
   */
  @java.lang.Override

  public java.lang.String getSecurityOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetSecurity().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; security = 4;</code>
   */
  @java.lang.Override

  public java.lang.String getSecurityOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetSecurity().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int SCHEMES_FIELD_NUMBER = 5;
  private com.google.protobuf.LazyStringList schemes_;
  /**
   * <code>repeated string schemes = 5;</code>
   * @return A list containing the schemes.
   */
  public com.google.protobuf.ProtocolStringList
      getSchemesList() {
    return schemes_;
  }
  /**
   * <code>repeated string schemes = 5;</code>
   * @return The count of schemes.
   */
  public int getSchemesCount() {
    return schemes_.size();
  }
  /**
   * <code>repeated string schemes = 5;</code>
   * @param index The index of the element to return.
   * @return The schemes at the given index.
   */
  public java.lang.String getSchemes(int index) {
    return schemes_.get(index);
  }
  /**
   * <code>repeated string schemes = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the schemes at the given index.
   */
  public com.google.protobuf.ByteString
      getSchemesBytes(int index) {
    return schemes_.getByteString(index);
  }

  public static final int METHODS_FIELD_NUMBER = 6;
  private com.google.protobuf.LazyStringList methods_;
  /**
   * <code>repeated string methods = 6;</code>
   * @return A list containing the methods.
   */
  public com.google.protobuf.ProtocolStringList
      getMethodsList() {
    return methods_;
  }
  /**
   * <code>repeated string methods = 6;</code>
   * @return The count of methods.
   */
  public int getMethodsCount() {
    return methods_.size();
  }
  /**
   * <code>repeated string methods = 6;</code>
   * @param index The index of the element to return.
   * @return The methods at the given index.
   */
  public java.lang.String getMethods(int index) {
    return methods_.get(index);
  }
  /**
   * <code>repeated string methods = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the methods at the given index.
   */
  public com.google.protobuf.ByteString
      getMethodsBytes(int index) {
    return methods_.getByteString(index);
  }

  public static final int SCOPESLIST_FIELD_NUMBER = 7;
  private java.util.List<org.wso2.choreo.connect.discovery.api.SecurityList> scopesList_;
  /**
   * <code>repeated .wso2.discovery.api.SecurityList scopesList = 7;</code>
   */
  @java.lang.Override
  public java.util.List<org.wso2.choreo.connect.discovery.api.SecurityList> getScopesListList() {
    return scopesList_;
  }
  /**
   * <code>repeated .wso2.discovery.api.SecurityList scopesList = 7;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.wso2.choreo.connect.discovery.api.SecurityListOrBuilder> 
      getScopesListOrBuilderList() {
    return scopesList_;
  }
  /**
   * <code>repeated .wso2.discovery.api.SecurityList scopesList = 7;</code>
   */
  @java.lang.Override
  public int getScopesListCount() {
    return scopesList_.size();
  }
  /**
   * <code>repeated .wso2.discovery.api.SecurityList scopesList = 7;</code>
   */
  @java.lang.Override
  public org.wso2.choreo.connect.discovery.api.SecurityList getScopesList(int index) {
    return scopesList_.get(index);
  }
  /**
   * <code>repeated .wso2.discovery.api.SecurityList scopesList = 7;</code>
   */
  @java.lang.Override
  public org.wso2.choreo.connect.discovery.api.SecurityListOrBuilder getScopesListOrBuilder(
      int index) {
    return scopesList_.get(index);
  }

  public static final int TIER_FIELD_NUMBER = 8;
  private volatile java.lang.Object tier_;
  /**
   * <code>string tier = 8;</code>
   * @return The tier.
   */
  @java.lang.Override
  public java.lang.String getTier() {
    java.lang.Object ref = tier_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tier_ = s;
      return s;
    }
  }
  /**
   * <code>string tier = 8;</code>
   * @return The bytes for tier.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTierBytes() {
    java.lang.Object ref = tier_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tier_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISABLESECURITY_FIELD_NUMBER = 9;
  private boolean disableSecurity_;
  /**
   * <code>bool disableSecurity = 9;</code>
   * @return The disableSecurity.
   */
  @java.lang.Override
  public boolean getDisableSecurity() {
    return disableSecurity_;
  }

  public static final int POLICIES_FIELD_NUMBER = 10;
  private org.wso2.choreo.connect.discovery.api.OperationPolicies policies_;
  /**
   * <code>.wso2.discovery.api.OperationPolicies policies = 10;</code>
   * @return Whether the policies field is set.
   */
  @java.lang.Override
  public boolean hasPolicies() {
    return policies_ != null;
  }
  /**
   * <code>.wso2.discovery.api.OperationPolicies policies = 10;</code>
   * @return The policies.
   */
  @java.lang.Override
  public org.wso2.choreo.connect.discovery.api.OperationPolicies getPolicies() {
    return policies_ == null ? org.wso2.choreo.connect.discovery.api.OperationPolicies.getDefaultInstance() : policies_;
  }
  /**
   * <code>.wso2.discovery.api.OperationPolicies policies = 10;</code>
   */
  @java.lang.Override
  public org.wso2.choreo.connect.discovery.api.OperationPoliciesOrBuilder getPoliciesOrBuilder() {
    return getPolicies();
  }

  public static final int ENDPOINTS_FIELD_NUMBER = 11;
  private org.wso2.choreo.connect.discovery.api.EndpointCluster endpoints_;
  /**
   * <code>.wso2.discovery.api.EndpointCluster endpoints = 11;</code>
   * @return Whether the endpoints field is set.
   */
  @java.lang.Override
  public boolean hasEndpoints() {
    return endpoints_ != null;
  }
  /**
   * <code>.wso2.discovery.api.EndpointCluster endpoints = 11;</code>
   * @return The endpoints.
   */
  @java.lang.Override
  public org.wso2.choreo.connect.discovery.api.EndpointCluster getEndpoints() {
    return endpoints_ == null ? org.wso2.choreo.connect.discovery.api.EndpointCluster.getDefaultInstance() : endpoints_;
  }
  /**
   * <code>.wso2.discovery.api.EndpointCluster endpoints = 11;</code>
   */
  @java.lang.Override
  public org.wso2.choreo.connect.discovery.api.EndpointClusterOrBuilder getEndpointsOrBuilder() {
    return getEndpoints();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getPathBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, path_);
    }
    for (int i = 0; i < endpointSecurity_.size(); i++) {
      output.writeMessage(3, endpointSecurity_.get(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetSecurity(),
        SecurityDefaultEntryHolder.defaultEntry,
        4);
    for (int i = 0; i < schemes_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, schemes_.getRaw(i));
    }
    for (int i = 0; i < methods_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, methods_.getRaw(i));
    }
    for (int i = 0; i < scopesList_.size(); i++) {
      output.writeMessage(7, scopesList_.get(i));
    }
    if (!getTierBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, tier_);
    }
    if (disableSecurity_ != false) {
      output.writeBool(9, disableSecurity_);
    }
    if (policies_ != null) {
      output.writeMessage(10, getPolicies());
    }
    if (endpoints_ != null) {
      output.writeMessage(11, getEndpoints());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getPathBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, path_);
    }
    for (int i = 0; i < endpointSecurity_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, endpointSecurity_.get(i));
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetSecurity().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      security__ = SecurityDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, security__);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < schemes_.size(); i++) {
        dataSize += computeStringSizeNoTag(schemes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getSchemesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < methods_.size(); i++) {
        dataSize += computeStringSizeNoTag(methods_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getMethodsList().size();
    }
    for (int i = 0; i < scopesList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, scopesList_.get(i));
    }
    if (!getTierBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, tier_);
    }
    if (disableSecurity_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, disableSecurity_);
    }
    if (policies_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getPolicies());
    }
    if (endpoints_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getEndpoints());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.wso2.choreo.connect.discovery.api.Resource)) {
      return super.equals(obj);
    }
    org.wso2.choreo.connect.discovery.api.Resource other = (org.wso2.choreo.connect.discovery.api.Resource) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getPath()
        .equals(other.getPath())) return false;
    if (!getEndpointSecurityList()
        .equals(other.getEndpointSecurityList())) return false;
    if (!internalGetSecurity().equals(
        other.internalGetSecurity())) return false;
    if (!getSchemesList()
        .equals(other.getSchemesList())) return false;
    if (!getMethodsList()
        .equals(other.getMethodsList())) return false;
    if (!getScopesListList()
        .equals(other.getScopesListList())) return false;
    if (!getTier()
        .equals(other.getTier())) return false;
    if (getDisableSecurity()
        != other.getDisableSecurity()) return false;
    if (hasPolicies() != other.hasPolicies()) return false;
    if (hasPolicies()) {
      if (!getPolicies()
          .equals(other.getPolicies())) return false;
    }
    if (hasEndpoints() != other.hasEndpoints()) return false;
    if (hasEndpoints()) {
      if (!getEndpoints()
          .equals(other.getEndpoints())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + PATH_FIELD_NUMBER;
    hash = (53 * hash) + getPath().hashCode();
    if (getEndpointSecurityCount() > 0) {
      hash = (37 * hash) + ENDPOINTSECURITY_FIELD_NUMBER;
      hash = (53 * hash) + getEndpointSecurityList().hashCode();
    }
    if (!internalGetSecurity().getMap().isEmpty()) {
      hash = (37 * hash) + SECURITY_FIELD_NUMBER;
      hash = (53 * hash) + internalGetSecurity().hashCode();
    }
    if (getSchemesCount() > 0) {
      hash = (37 * hash) + SCHEMES_FIELD_NUMBER;
      hash = (53 * hash) + getSchemesList().hashCode();
    }
    if (getMethodsCount() > 0) {
      hash = (37 * hash) + METHODS_FIELD_NUMBER;
      hash = (53 * hash) + getMethodsList().hashCode();
    }
    if (getScopesListCount() > 0) {
      hash = (37 * hash) + SCOPESLIST_FIELD_NUMBER;
      hash = (53 * hash) + getScopesListList().hashCode();
    }
    hash = (37 * hash) + TIER_FIELD_NUMBER;
    hash = (53 * hash) + getTier().hashCode();
    hash = (37 * hash) + DISABLESECURITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDisableSecurity());
    if (hasPolicies()) {
      hash = (37 * hash) + POLICIES_FIELD_NUMBER;
      hash = (53 * hash) + getPolicies().hashCode();
    }
    if (hasEndpoints()) {
      hash = (37 * hash) + ENDPOINTS_FIELD_NUMBER;
      hash = (53 * hash) + getEndpoints().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.wso2.choreo.connect.discovery.api.Resource parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.wso2.choreo.connect.discovery.api.Resource parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.wso2.choreo.connect.discovery.api.Resource parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.wso2.choreo.connect.discovery.api.Resource parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.wso2.choreo.connect.discovery.api.Resource parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.wso2.choreo.connect.discovery.api.Resource parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.wso2.choreo.connect.discovery.api.Resource parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.wso2.choreo.connect.discovery.api.Resource parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.wso2.choreo.connect.discovery.api.Resource parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.wso2.choreo.connect.discovery.api.Resource parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.wso2.choreo.connect.discovery.api.Resource parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.wso2.choreo.connect.discovery.api.Resource parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.wso2.choreo.connect.discovery.api.Resource prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Resource config model
   * </pre>
   *
   * Protobuf type {@code wso2.discovery.api.Resource}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:wso2.discovery.api.Resource)
      org.wso2.choreo.connect.discovery.api.ResourceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.wso2.choreo.connect.discovery.api.ResourceProto.internal_static_wso2_discovery_api_Resource_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetSecurity();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetMutableSecurity();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.wso2.choreo.connect.discovery.api.ResourceProto.internal_static_wso2_discovery_api_Resource_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.wso2.choreo.connect.discovery.api.Resource.class, org.wso2.choreo.connect.discovery.api.Resource.Builder.class);
    }

    // Construct using org.wso2.choreo.connect.discovery.api.Resource.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEndpointSecurityFieldBuilder();
        getScopesListFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      path_ = "";

      if (endpointSecurityBuilder_ == null) {
        endpointSecurity_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        endpointSecurityBuilder_.clear();
      }
      internalGetMutableSecurity().clear();
      schemes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      methods_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      if (scopesListBuilder_ == null) {
        scopesList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        scopesListBuilder_.clear();
      }
      tier_ = "";

      disableSecurity_ = false;

      if (policiesBuilder_ == null) {
        policies_ = null;
      } else {
        policies_ = null;
        policiesBuilder_ = null;
      }
      if (endpointsBuilder_ == null) {
        endpoints_ = null;
      } else {
        endpoints_ = null;
        endpointsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.wso2.choreo.connect.discovery.api.ResourceProto.internal_static_wso2_discovery_api_Resource_descriptor;
    }

    @java.lang.Override
    public org.wso2.choreo.connect.discovery.api.Resource getDefaultInstanceForType() {
      return org.wso2.choreo.connect.discovery.api.Resource.getDefaultInstance();
    }

    @java.lang.Override
    public org.wso2.choreo.connect.discovery.api.Resource build() {
      org.wso2.choreo.connect.discovery.api.Resource result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.wso2.choreo.connect.discovery.api.Resource buildPartial() {
      org.wso2.choreo.connect.discovery.api.Resource result = new org.wso2.choreo.connect.discovery.api.Resource(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.path_ = path_;
      if (endpointSecurityBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          endpointSecurity_ = java.util.Collections.unmodifiableList(endpointSecurity_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.endpointSecurity_ = endpointSecurity_;
      } else {
        result.endpointSecurity_ = endpointSecurityBuilder_.build();
      }
      result.security_ = internalGetSecurity();
      result.security_.makeImmutable();
      if (((bitField0_ & 0x00000004) != 0)) {
        schemes_ = schemes_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.schemes_ = schemes_;
      if (((bitField0_ & 0x00000008) != 0)) {
        methods_ = methods_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.methods_ = methods_;
      if (scopesListBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          scopesList_ = java.util.Collections.unmodifiableList(scopesList_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.scopesList_ = scopesList_;
      } else {
        result.scopesList_ = scopesListBuilder_.build();
      }
      result.tier_ = tier_;
      result.disableSecurity_ = disableSecurity_;
      if (policiesBuilder_ == null) {
        result.policies_ = policies_;
      } else {
        result.policies_ = policiesBuilder_.build();
      }
      if (endpointsBuilder_ == null) {
        result.endpoints_ = endpoints_;
      } else {
        result.endpoints_ = endpointsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.wso2.choreo.connect.discovery.api.Resource) {
        return mergeFrom((org.wso2.choreo.connect.discovery.api.Resource)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.wso2.choreo.connect.discovery.api.Resource other) {
      if (other == org.wso2.choreo.connect.discovery.api.Resource.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getPath().isEmpty()) {
        path_ = other.path_;
        onChanged();
      }
      if (endpointSecurityBuilder_ == null) {
        if (!other.endpointSecurity_.isEmpty()) {
          if (endpointSecurity_.isEmpty()) {
            endpointSecurity_ = other.endpointSecurity_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEndpointSecurityIsMutable();
            endpointSecurity_.addAll(other.endpointSecurity_);
          }
          onChanged();
        }
      } else {
        if (!other.endpointSecurity_.isEmpty()) {
          if (endpointSecurityBuilder_.isEmpty()) {
            endpointSecurityBuilder_.dispose();
            endpointSecurityBuilder_ = null;
            endpointSecurity_ = other.endpointSecurity_;
            bitField0_ = (bitField0_ & ~0x00000001);
            endpointSecurityBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEndpointSecurityFieldBuilder() : null;
          } else {
            endpointSecurityBuilder_.addAllMessages(other.endpointSecurity_);
          }
        }
      }
      internalGetMutableSecurity().mergeFrom(
          other.internalGetSecurity());
      if (!other.schemes_.isEmpty()) {
        if (schemes_.isEmpty()) {
          schemes_ = other.schemes_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureSchemesIsMutable();
          schemes_.addAll(other.schemes_);
        }
        onChanged();
      }
      if (!other.methods_.isEmpty()) {
        if (methods_.isEmpty()) {
          methods_ = other.methods_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureMethodsIsMutable();
          methods_.addAll(other.methods_);
        }
        onChanged();
      }
      if (scopesListBuilder_ == null) {
        if (!other.scopesList_.isEmpty()) {
          if (scopesList_.isEmpty()) {
            scopesList_ = other.scopesList_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureScopesListIsMutable();
            scopesList_.addAll(other.scopesList_);
          }
          onChanged();
        }
      } else {
        if (!other.scopesList_.isEmpty()) {
          if (scopesListBuilder_.isEmpty()) {
            scopesListBuilder_.dispose();
            scopesListBuilder_ = null;
            scopesList_ = other.scopesList_;
            bitField0_ = (bitField0_ & ~0x00000010);
            scopesListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getScopesListFieldBuilder() : null;
          } else {
            scopesListBuilder_.addAllMessages(other.scopesList_);
          }
        }
      }
      if (!other.getTier().isEmpty()) {
        tier_ = other.tier_;
        onChanged();
      }
      if (other.getDisableSecurity() != false) {
        setDisableSecurity(other.getDisableSecurity());
      }
      if (other.hasPolicies()) {
        mergePolicies(other.getPolicies());
      }
      if (other.hasEndpoints()) {
        mergeEndpoints(other.getEndpoints());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.wso2.choreo.connect.discovery.api.Resource parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.wso2.choreo.connect.discovery.api.Resource) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object path_ = "";
    /**
     * <code>string path = 2;</code>
     * @return The path.
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        path_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string path = 2;</code>
     * @return The bytes for path.
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string path = 2;</code>
     * @param value The path to set.
     * @return This builder for chaining.
     */
    public Builder setPath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      path_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string path = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPath() {
      
      path_ = getDefaultInstance().getPath();
      onChanged();
      return this;
    }
    /**
     * <code>string path = 2;</code>
     * @param value The bytes for path to set.
     * @return This builder for chaining.
     */
    public Builder setPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      path_ = value;
      onChanged();
      return this;
    }

    private java.util.List<org.wso2.choreo.connect.discovery.api.SecurityInfo> endpointSecurity_ =
      java.util.Collections.emptyList();
    private void ensureEndpointSecurityIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        endpointSecurity_ = new java.util.ArrayList<org.wso2.choreo.connect.discovery.api.SecurityInfo>(endpointSecurity_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.wso2.choreo.connect.discovery.api.SecurityInfo, org.wso2.choreo.connect.discovery.api.SecurityInfo.Builder, org.wso2.choreo.connect.discovery.api.SecurityInfoOrBuilder> endpointSecurityBuilder_;

    /**
     * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 3;</code>
     */
    public java.util.List<org.wso2.choreo.connect.discovery.api.SecurityInfo> getEndpointSecurityList() {
      if (endpointSecurityBuilder_ == null) {
        return java.util.Collections.unmodifiableList(endpointSecurity_);
      } else {
        return endpointSecurityBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 3;</code>
     */
    public int getEndpointSecurityCount() {
      if (endpointSecurityBuilder_ == null) {
        return endpointSecurity_.size();
      } else {
        return endpointSecurityBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 3;</code>
     */
    public org.wso2.choreo.connect.discovery.api.SecurityInfo getEndpointSecurity(int index) {
      if (endpointSecurityBuilder_ == null) {
        return endpointSecurity_.get(index);
      } else {
        return endpointSecurityBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 3;</code>
     */
    public Builder setEndpointSecurity(
        int index, org.wso2.choreo.connect.discovery.api.SecurityInfo value) {
      if (endpointSecurityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEndpointSecurityIsMutable();
        endpointSecurity_.set(index, value);
        onChanged();
      } else {
        endpointSecurityBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 3;</code>
     */
    public Builder setEndpointSecurity(
        int index, org.wso2.choreo.connect.discovery.api.SecurityInfo.Builder builderForValue) {
      if (endpointSecurityBuilder_ == null) {
        ensureEndpointSecurityIsMutable();
        endpointSecurity_.set(index, builderForValue.build());
        onChanged();
      } else {
        endpointSecurityBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 3;</code>
     */
    public Builder addEndpointSecurity(org.wso2.choreo.connect.discovery.api.SecurityInfo value) {
      if (endpointSecurityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEndpointSecurityIsMutable();
        endpointSecurity_.add(value);
        onChanged();
      } else {
        endpointSecurityBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 3;</code>
     */
    public Builder addEndpointSecurity(
        int index, org.wso2.choreo.connect.discovery.api.SecurityInfo value) {
      if (endpointSecurityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEndpointSecurityIsMutable();
        endpointSecurity_.add(index, value);
        onChanged();
      } else {
        endpointSecurityBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 3;</code>
     */
    public Builder addEndpointSecurity(
        org.wso2.choreo.connect.discovery.api.SecurityInfo.Builder builderForValue) {
      if (endpointSecurityBuilder_ == null) {
        ensureEndpointSecurityIsMutable();
        endpointSecurity_.add(builderForValue.build());
        onChanged();
      } else {
        endpointSecurityBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 3;</code>
     */
    public Builder addEndpointSecurity(
        int index, org.wso2.choreo.connect.discovery.api.SecurityInfo.Builder builderForValue) {
      if (endpointSecurityBuilder_ == null) {
        ensureEndpointSecurityIsMutable();
        endpointSecurity_.add(index, builderForValue.build());
        onChanged();
      } else {
        endpointSecurityBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 3;</code>
     */
    public Builder addAllEndpointSecurity(
        java.lang.Iterable<? extends org.wso2.choreo.connect.discovery.api.SecurityInfo> values) {
      if (endpointSecurityBuilder_ == null) {
        ensureEndpointSecurityIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, endpointSecurity_);
        onChanged();
      } else {
        endpointSecurityBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 3;</code>
     */
    public Builder clearEndpointSecurity() {
      if (endpointSecurityBuilder_ == null) {
        endpointSecurity_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        endpointSecurityBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 3;</code>
     */
    public Builder removeEndpointSecurity(int index) {
      if (endpointSecurityBuilder_ == null) {
        ensureEndpointSecurityIsMutable();
        endpointSecurity_.remove(index);
        onChanged();
      } else {
        endpointSecurityBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 3;</code>
     */
    public org.wso2.choreo.connect.discovery.api.SecurityInfo.Builder getEndpointSecurityBuilder(
        int index) {
      return getEndpointSecurityFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 3;</code>
     */
    public org.wso2.choreo.connect.discovery.api.SecurityInfoOrBuilder getEndpointSecurityOrBuilder(
        int index) {
      if (endpointSecurityBuilder_ == null) {
        return endpointSecurity_.get(index);  } else {
        return endpointSecurityBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 3;</code>
     */
    public java.util.List<? extends org.wso2.choreo.connect.discovery.api.SecurityInfoOrBuilder> 
         getEndpointSecurityOrBuilderList() {
      if (endpointSecurityBuilder_ != null) {
        return endpointSecurityBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(endpointSecurity_);
      }
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 3;</code>
     */
    public org.wso2.choreo.connect.discovery.api.SecurityInfo.Builder addEndpointSecurityBuilder() {
      return getEndpointSecurityFieldBuilder().addBuilder(
          org.wso2.choreo.connect.discovery.api.SecurityInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 3;</code>
     */
    public org.wso2.choreo.connect.discovery.api.SecurityInfo.Builder addEndpointSecurityBuilder(
        int index) {
      return getEndpointSecurityFieldBuilder().addBuilder(
          index, org.wso2.choreo.connect.discovery.api.SecurityInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 3;</code>
     */
    public java.util.List<org.wso2.choreo.connect.discovery.api.SecurityInfo.Builder> 
         getEndpointSecurityBuilderList() {
      return getEndpointSecurityFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.wso2.choreo.connect.discovery.api.SecurityInfo, org.wso2.choreo.connect.discovery.api.SecurityInfo.Builder, org.wso2.choreo.connect.discovery.api.SecurityInfoOrBuilder> 
        getEndpointSecurityFieldBuilder() {
      if (endpointSecurityBuilder_ == null) {
        endpointSecurityBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.wso2.choreo.connect.discovery.api.SecurityInfo, org.wso2.choreo.connect.discovery.api.SecurityInfo.Builder, org.wso2.choreo.connect.discovery.api.SecurityInfoOrBuilder>(
                endpointSecurity_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        endpointSecurity_ = null;
      }
      return endpointSecurityBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> security_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetSecurity() {
      if (security_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SecurityDefaultEntryHolder.defaultEntry);
      }
      return security_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableSecurity() {
      onChanged();;
      if (security_ == null) {
        security_ = com.google.protobuf.MapField.newMapField(
            SecurityDefaultEntryHolder.defaultEntry);
      }
      if (!security_.isMutable()) {
        security_ = security_.copy();
      }
      return security_;
    }

    public int getSecurityCount() {
      return internalGetSecurity().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; security = 4;</code>
     */

    @java.lang.Override
    public boolean containsSecurity(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetSecurity().getMap().containsKey(key);
    }
    /**
     * Use {@link #getSecurityMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getSecurity() {
      return getSecurityMap();
    }
    /**
     * <code>map&lt;string, string&gt; security = 4;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getSecurityMap() {
      return internalGetSecurity().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; security = 4;</code>
     */
    @java.lang.Override

    public java.lang.String getSecurityOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetSecurity().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; security = 4;</code>
     */
    @java.lang.Override

    public java.lang.String getSecurityOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetSecurity().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearSecurity() {
      internalGetMutableSecurity().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; security = 4;</code>
     */

    public Builder removeSecurity(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableSecurity().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableSecurity() {
      return internalGetMutableSecurity().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; security = 4;</code>
     */
    public Builder putSecurity(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableSecurity().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; security = 4;</code>
     */

    public Builder putAllSecurity(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableSecurity().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.LazyStringList schemes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureSchemesIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        schemes_ = new com.google.protobuf.LazyStringArrayList(schemes_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated string schemes = 5;</code>
     * @return A list containing the schemes.
     */
    public com.google.protobuf.ProtocolStringList
        getSchemesList() {
      return schemes_.getUnmodifiableView();
    }
    /**
     * <code>repeated string schemes = 5;</code>
     * @return The count of schemes.
     */
    public int getSchemesCount() {
      return schemes_.size();
    }
    /**
     * <code>repeated string schemes = 5;</code>
     * @param index The index of the element to return.
     * @return The schemes at the given index.
     */
    public java.lang.String getSchemes(int index) {
      return schemes_.get(index);
    }
    /**
     * <code>repeated string schemes = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the schemes at the given index.
     */
    public com.google.protobuf.ByteString
        getSchemesBytes(int index) {
      return schemes_.getByteString(index);
    }
    /**
     * <code>repeated string schemes = 5;</code>
     * @param index The index to set the value at.
     * @param value The schemes to set.
     * @return This builder for chaining.
     */
    public Builder setSchemes(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSchemesIsMutable();
      schemes_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string schemes = 5;</code>
     * @param value The schemes to add.
     * @return This builder for chaining.
     */
    public Builder addSchemes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSchemesIsMutable();
      schemes_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string schemes = 5;</code>
     * @param values The schemes to add.
     * @return This builder for chaining.
     */
    public Builder addAllSchemes(
        java.lang.Iterable<java.lang.String> values) {
      ensureSchemesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, schemes_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string schemes = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSchemes() {
      schemes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string schemes = 5;</code>
     * @param value The bytes of the schemes to add.
     * @return This builder for chaining.
     */
    public Builder addSchemesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureSchemesIsMutable();
      schemes_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList methods_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureMethodsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        methods_ = new com.google.protobuf.LazyStringArrayList(methods_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <code>repeated string methods = 6;</code>
     * @return A list containing the methods.
     */
    public com.google.protobuf.ProtocolStringList
        getMethodsList() {
      return methods_.getUnmodifiableView();
    }
    /**
     * <code>repeated string methods = 6;</code>
     * @return The count of methods.
     */
    public int getMethodsCount() {
      return methods_.size();
    }
    /**
     * <code>repeated string methods = 6;</code>
     * @param index The index of the element to return.
     * @return The methods at the given index.
     */
    public java.lang.String getMethods(int index) {
      return methods_.get(index);
    }
    /**
     * <code>repeated string methods = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the methods at the given index.
     */
    public com.google.protobuf.ByteString
        getMethodsBytes(int index) {
      return methods_.getByteString(index);
    }
    /**
     * <code>repeated string methods = 6;</code>
     * @param index The index to set the value at.
     * @param value The methods to set.
     * @return This builder for chaining.
     */
    public Builder setMethods(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMethodsIsMutable();
      methods_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string methods = 6;</code>
     * @param value The methods to add.
     * @return This builder for chaining.
     */
    public Builder addMethods(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMethodsIsMutable();
      methods_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string methods = 6;</code>
     * @param values The methods to add.
     * @return This builder for chaining.
     */
    public Builder addAllMethods(
        java.lang.Iterable<java.lang.String> values) {
      ensureMethodsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, methods_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string methods = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMethods() {
      methods_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string methods = 6;</code>
     * @param value The bytes of the methods to add.
     * @return This builder for chaining.
     */
    public Builder addMethodsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureMethodsIsMutable();
      methods_.add(value);
      onChanged();
      return this;
    }

    private java.util.List<org.wso2.choreo.connect.discovery.api.SecurityList> scopesList_ =
      java.util.Collections.emptyList();
    private void ensureScopesListIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        scopesList_ = new java.util.ArrayList<org.wso2.choreo.connect.discovery.api.SecurityList>(scopesList_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.wso2.choreo.connect.discovery.api.SecurityList, org.wso2.choreo.connect.discovery.api.SecurityList.Builder, org.wso2.choreo.connect.discovery.api.SecurityListOrBuilder> scopesListBuilder_;

    /**
     * <code>repeated .wso2.discovery.api.SecurityList scopesList = 7;</code>
     */
    public java.util.List<org.wso2.choreo.connect.discovery.api.SecurityList> getScopesListList() {
      if (scopesListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(scopesList_);
      } else {
        return scopesListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityList scopesList = 7;</code>
     */
    public int getScopesListCount() {
      if (scopesListBuilder_ == null) {
        return scopesList_.size();
      } else {
        return scopesListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityList scopesList = 7;</code>
     */
    public org.wso2.choreo.connect.discovery.api.SecurityList getScopesList(int index) {
      if (scopesListBuilder_ == null) {
        return scopesList_.get(index);
      } else {
        return scopesListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityList scopesList = 7;</code>
     */
    public Builder setScopesList(
        int index, org.wso2.choreo.connect.discovery.api.SecurityList value) {
      if (scopesListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureScopesListIsMutable();
        scopesList_.set(index, value);
        onChanged();
      } else {
        scopesListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityList scopesList = 7;</code>
     */
    public Builder setScopesList(
        int index, org.wso2.choreo.connect.discovery.api.SecurityList.Builder builderForValue) {
      if (scopesListBuilder_ == null) {
        ensureScopesListIsMutable();
        scopesList_.set(index, builderForValue.build());
        onChanged();
      } else {
        scopesListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityList scopesList = 7;</code>
     */
    public Builder addScopesList(org.wso2.choreo.connect.discovery.api.SecurityList value) {
      if (scopesListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureScopesListIsMutable();
        scopesList_.add(value);
        onChanged();
      } else {
        scopesListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityList scopesList = 7;</code>
     */
    public Builder addScopesList(
        int index, org.wso2.choreo.connect.discovery.api.SecurityList value) {
      if (scopesListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureScopesListIsMutable();
        scopesList_.add(index, value);
        onChanged();
      } else {
        scopesListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityList scopesList = 7;</code>
     */
    public Builder addScopesList(
        org.wso2.choreo.connect.discovery.api.SecurityList.Builder builderForValue) {
      if (scopesListBuilder_ == null) {
        ensureScopesListIsMutable();
        scopesList_.add(builderForValue.build());
        onChanged();
      } else {
        scopesListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityList scopesList = 7;</code>
     */
    public Builder addScopesList(
        int index, org.wso2.choreo.connect.discovery.api.SecurityList.Builder builderForValue) {
      if (scopesListBuilder_ == null) {
        ensureScopesListIsMutable();
        scopesList_.add(index, builderForValue.build());
        onChanged();
      } else {
        scopesListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityList scopesList = 7;</code>
     */
    public Builder addAllScopesList(
        java.lang.Iterable<? extends org.wso2.choreo.connect.discovery.api.SecurityList> values) {
      if (scopesListBuilder_ == null) {
        ensureScopesListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, scopesList_);
        onChanged();
      } else {
        scopesListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityList scopesList = 7;</code>
     */
    public Builder clearScopesList() {
      if (scopesListBuilder_ == null) {
        scopesList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        scopesListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityList scopesList = 7;</code>
     */
    public Builder removeScopesList(int index) {
      if (scopesListBuilder_ == null) {
        ensureScopesListIsMutable();
        scopesList_.remove(index);
        onChanged();
      } else {
        scopesListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityList scopesList = 7;</code>
     */
    public org.wso2.choreo.connect.discovery.api.SecurityList.Builder getScopesListBuilder(
        int index) {
      return getScopesListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityList scopesList = 7;</code>
     */
    public org.wso2.choreo.connect.discovery.api.SecurityListOrBuilder getScopesListOrBuilder(
        int index) {
      if (scopesListBuilder_ == null) {
        return scopesList_.get(index);  } else {
        return scopesListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityList scopesList = 7;</code>
     */
    public java.util.List<? extends org.wso2.choreo.connect.discovery.api.SecurityListOrBuilder> 
         getScopesListOrBuilderList() {
      if (scopesListBuilder_ != null) {
        return scopesListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(scopesList_);
      }
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityList scopesList = 7;</code>
     */
    public org.wso2.choreo.connect.discovery.api.SecurityList.Builder addScopesListBuilder() {
      return getScopesListFieldBuilder().addBuilder(
          org.wso2.choreo.connect.discovery.api.SecurityList.getDefaultInstance());
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityList scopesList = 7;</code>
     */
    public org.wso2.choreo.connect.discovery.api.SecurityList.Builder addScopesListBuilder(
        int index) {
      return getScopesListFieldBuilder().addBuilder(
          index, org.wso2.choreo.connect.discovery.api.SecurityList.getDefaultInstance());
    }
    /**
     * <code>repeated .wso2.discovery.api.SecurityList scopesList = 7;</code>
     */
    public java.util.List<org.wso2.choreo.connect.discovery.api.SecurityList.Builder> 
         getScopesListBuilderList() {
      return getScopesListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.wso2.choreo.connect.discovery.api.SecurityList, org.wso2.choreo.connect.discovery.api.SecurityList.Builder, org.wso2.choreo.connect.discovery.api.SecurityListOrBuilder> 
        getScopesListFieldBuilder() {
      if (scopesListBuilder_ == null) {
        scopesListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.wso2.choreo.connect.discovery.api.SecurityList, org.wso2.choreo.connect.discovery.api.SecurityList.Builder, org.wso2.choreo.connect.discovery.api.SecurityListOrBuilder>(
                scopesList_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        scopesList_ = null;
      }
      return scopesListBuilder_;
    }

    private java.lang.Object tier_ = "";
    /**
     * <code>string tier = 8;</code>
     * @return The tier.
     */
    public java.lang.String getTier() {
      java.lang.Object ref = tier_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tier_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tier = 8;</code>
     * @return The bytes for tier.
     */
    public com.google.protobuf.ByteString
        getTierBytes() {
      java.lang.Object ref = tier_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tier = 8;</code>
     * @param value The tier to set.
     * @return This builder for chaining.
     */
    public Builder setTier(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tier_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tier = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTier() {
      
      tier_ = getDefaultInstance().getTier();
      onChanged();
      return this;
    }
    /**
     * <code>string tier = 8;</code>
     * @param value The bytes for tier to set.
     * @return This builder for chaining.
     */
    public Builder setTierBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tier_ = value;
      onChanged();
      return this;
    }

    private boolean disableSecurity_ ;
    /**
     * <code>bool disableSecurity = 9;</code>
     * @return The disableSecurity.
     */
    @java.lang.Override
    public boolean getDisableSecurity() {
      return disableSecurity_;
    }
    /**
     * <code>bool disableSecurity = 9;</code>
     * @param value The disableSecurity to set.
     * @return This builder for chaining.
     */
    public Builder setDisableSecurity(boolean value) {
      
      disableSecurity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool disableSecurity = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisableSecurity() {
      
      disableSecurity_ = false;
      onChanged();
      return this;
    }

    private org.wso2.choreo.connect.discovery.api.OperationPolicies policies_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.wso2.choreo.connect.discovery.api.OperationPolicies, org.wso2.choreo.connect.discovery.api.OperationPolicies.Builder, org.wso2.choreo.connect.discovery.api.OperationPoliciesOrBuilder> policiesBuilder_;
    /**
     * <code>.wso2.discovery.api.OperationPolicies policies = 10;</code>
     * @return Whether the policies field is set.
     */
    public boolean hasPolicies() {
      return policiesBuilder_ != null || policies_ != null;
    }
    /**
     * <code>.wso2.discovery.api.OperationPolicies policies = 10;</code>
     * @return The policies.
     */
    public org.wso2.choreo.connect.discovery.api.OperationPolicies getPolicies() {
      if (policiesBuilder_ == null) {
        return policies_ == null ? org.wso2.choreo.connect.discovery.api.OperationPolicies.getDefaultInstance() : policies_;
      } else {
        return policiesBuilder_.getMessage();
      }
    }
    /**
     * <code>.wso2.discovery.api.OperationPolicies policies = 10;</code>
     */
    public Builder setPolicies(org.wso2.choreo.connect.discovery.api.OperationPolicies value) {
      if (policiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        policies_ = value;
        onChanged();
      } else {
        policiesBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.wso2.discovery.api.OperationPolicies policies = 10;</code>
     */
    public Builder setPolicies(
        org.wso2.choreo.connect.discovery.api.OperationPolicies.Builder builderForValue) {
      if (policiesBuilder_ == null) {
        policies_ = builderForValue.build();
        onChanged();
      } else {
        policiesBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.wso2.discovery.api.OperationPolicies policies = 10;</code>
     */
    public Builder mergePolicies(org.wso2.choreo.connect.discovery.api.OperationPolicies value) {
      if (policiesBuilder_ == null) {
        if (policies_ != null) {
          policies_ =
            org.wso2.choreo.connect.discovery.api.OperationPolicies.newBuilder(policies_).mergeFrom(value).buildPartial();
        } else {
          policies_ = value;
        }
        onChanged();
      } else {
        policiesBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.wso2.discovery.api.OperationPolicies policies = 10;</code>
     */
    public Builder clearPolicies() {
      if (policiesBuilder_ == null) {
        policies_ = null;
        onChanged();
      } else {
        policies_ = null;
        policiesBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.wso2.discovery.api.OperationPolicies policies = 10;</code>
     */
    public org.wso2.choreo.connect.discovery.api.OperationPolicies.Builder getPoliciesBuilder() {
      
      onChanged();
      return getPoliciesFieldBuilder().getBuilder();
    }
    /**
     * <code>.wso2.discovery.api.OperationPolicies policies = 10;</code>
     */
    public org.wso2.choreo.connect.discovery.api.OperationPoliciesOrBuilder getPoliciesOrBuilder() {
      if (policiesBuilder_ != null) {
        return policiesBuilder_.getMessageOrBuilder();
      } else {
        return policies_ == null ?
            org.wso2.choreo.connect.discovery.api.OperationPolicies.getDefaultInstance() : policies_;
      }
    }
    /**
     * <code>.wso2.discovery.api.OperationPolicies policies = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.wso2.choreo.connect.discovery.api.OperationPolicies, org.wso2.choreo.connect.discovery.api.OperationPolicies.Builder, org.wso2.choreo.connect.discovery.api.OperationPoliciesOrBuilder> 
        getPoliciesFieldBuilder() {
      if (policiesBuilder_ == null) {
        policiesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.wso2.choreo.connect.discovery.api.OperationPolicies, org.wso2.choreo.connect.discovery.api.OperationPolicies.Builder, org.wso2.choreo.connect.discovery.api.OperationPoliciesOrBuilder>(
                getPolicies(),
                getParentForChildren(),
                isClean());
        policies_ = null;
      }
      return policiesBuilder_;
    }

    private org.wso2.choreo.connect.discovery.api.EndpointCluster endpoints_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.wso2.choreo.connect.discovery.api.EndpointCluster, org.wso2.choreo.connect.discovery.api.EndpointCluster.Builder, org.wso2.choreo.connect.discovery.api.EndpointClusterOrBuilder> endpointsBuilder_;
    /**
     * <code>.wso2.discovery.api.EndpointCluster endpoints = 11;</code>
     * @return Whether the endpoints field is set.
     */
    public boolean hasEndpoints() {
      return endpointsBuilder_ != null || endpoints_ != null;
    }
    /**
     * <code>.wso2.discovery.api.EndpointCluster endpoints = 11;</code>
     * @return The endpoints.
     */
    public org.wso2.choreo.connect.discovery.api.EndpointCluster getEndpoints() {
      if (endpointsBuilder_ == null) {
        return endpoints_ == null ? org.wso2.choreo.connect.discovery.api.EndpointCluster.getDefaultInstance() : endpoints_;
      } else {
        return endpointsBuilder_.getMessage();
      }
    }
    /**
     * <code>.wso2.discovery.api.EndpointCluster endpoints = 11;</code>
     */
    public Builder setEndpoints(org.wso2.choreo.connect.discovery.api.EndpointCluster value) {
      if (endpointsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        endpoints_ = value;
        onChanged();
      } else {
        endpointsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.wso2.discovery.api.EndpointCluster endpoints = 11;</code>
     */
    public Builder setEndpoints(
        org.wso2.choreo.connect.discovery.api.EndpointCluster.Builder builderForValue) {
      if (endpointsBuilder_ == null) {
        endpoints_ = builderForValue.build();
        onChanged();
      } else {
        endpointsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.wso2.discovery.api.EndpointCluster endpoints = 11;</code>
     */
    public Builder mergeEndpoints(org.wso2.choreo.connect.discovery.api.EndpointCluster value) {
      if (endpointsBuilder_ == null) {
        if (endpoints_ != null) {
          endpoints_ =
            org.wso2.choreo.connect.discovery.api.EndpointCluster.newBuilder(endpoints_).mergeFrom(value).buildPartial();
        } else {
          endpoints_ = value;
        }
        onChanged();
      } else {
        endpointsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.wso2.discovery.api.EndpointCluster endpoints = 11;</code>
     */
    public Builder clearEndpoints() {
      if (endpointsBuilder_ == null) {
        endpoints_ = null;
        onChanged();
      } else {
        endpoints_ = null;
        endpointsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.wso2.discovery.api.EndpointCluster endpoints = 11;</code>
     */
    public org.wso2.choreo.connect.discovery.api.EndpointCluster.Builder getEndpointsBuilder() {
      
      onChanged();
      return getEndpointsFieldBuilder().getBuilder();
    }
    /**
     * <code>.wso2.discovery.api.EndpointCluster endpoints = 11;</code>
     */
    public org.wso2.choreo.connect.discovery.api.EndpointClusterOrBuilder getEndpointsOrBuilder() {
      if (endpointsBuilder_ != null) {
        return endpointsBuilder_.getMessageOrBuilder();
      } else {
        return endpoints_ == null ?
            org.wso2.choreo.connect.discovery.api.EndpointCluster.getDefaultInstance() : endpoints_;
      }
    }
    /**
     * <code>.wso2.discovery.api.EndpointCluster endpoints = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.wso2.choreo.connect.discovery.api.EndpointCluster, org.wso2.choreo.connect.discovery.api.EndpointCluster.Builder, org.wso2.choreo.connect.discovery.api.EndpointClusterOrBuilder> 
        getEndpointsFieldBuilder() {
      if (endpointsBuilder_ == null) {
        endpointsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.wso2.choreo.connect.discovery.api.EndpointCluster, org.wso2.choreo.connect.discovery.api.EndpointCluster.Builder, org.wso2.choreo.connect.discovery.api.EndpointClusterOrBuilder>(
                getEndpoints(),
                getParentForChildren(),
                isClean());
        endpoints_ = null;
      }
      return endpointsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:wso2.discovery.api.Resource)
  }

  // @@protoc_insertion_point(class_scope:wso2.discovery.api.Resource)
  private static final org.wso2.choreo.connect.discovery.api.Resource DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.wso2.choreo.connect.discovery.api.Resource();
  }

  public static org.wso2.choreo.connect.discovery.api.Resource getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Resource>
      PARSER = new com.google.protobuf.AbstractParser<Resource>() {
    @java.lang.Override
    public Resource parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Resource(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Resource> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Resource> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.wso2.choreo.connect.discovery.api.Resource getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

